import { useEffect, useMemo, useState } from "react";
import { apiFetch } from "../api";
import { PageHeader, MetricCard, StatusBadge, ErrorBlock, LoadingBlock } from "../components/Common";

const LABELS = { food_packets:"Food Packets", water_litres:"Water Litres", medical_kits:"Medical Kits", shelter_people:"Shelter Capacity" };

export default function OptimizationPlanner() {
  const [types,setTypes]=useState([]), [type,setType]=useState(""), [records,setRecords]=useState([]), [selected,setSelected]=useState([]), [overrides,setOverrides]=useState({});
  const [transport,setTransport]=useState(1), [stock,setStock]=useState({food:"",water:"",medical:"",shelter:""});
  const [result,setResult]=useState(null), [loading,setLoading]=useState(false), [error,setError]=useState("");
  useEffect(()=>{ apiFetch("/disasters/types").then(d=>setTypes(d.supported_disasters||[])).catch(e=>setError(e.message)); apiFetch("/inventory").then(d=>{ const r=d.resources||{}; setStock({food:r.food_packets?.quantity??"",water:r.water_litres?.quantity??"",medical:r.medical_kits?.quantity??"",shelter:r.shelter_capacity?.quantity??""}); }).catch(()=>{}); },[]);
  useEffect(()=>{ const p=type?`/disasters?disaster_type=${encodeURIComponent(type)}&limit=20`:"/disasters?limit=20"; apiFetch(p).then(d=>{setRecords(d.data||[]);setSelected([]);setOverrides({});setResult(null);}).catch(e=>setError(e.message)); },[type]);
  const selectedRows=useMemo(()=>records.filter(r=>selected.includes(r.row_id)),[records,selected]);
  function toggle(id){ setSelected(cur=>cur.includes(id)?cur.filter(x=>x!==id):cur.length>=8?(setError("Select at most 8 zones."),cur):[...cur,id]); }
  async function run(){ if(selected.length<2){setError("Select at least 2 disaster zones.");return;} setLoading(true);setError("");setResult(null); const po={}; selected.forEach(id=>po[id]=Number(overrides[id]??1)); try{ const data=await apiFetch("/optimization/resource-allocation",{method:"POST",body:JSON.stringify({row_ids:selected,food_packets_available:Number(stock.food),water_litres_available:Number(stock.water),medical_kits_available:Number(stock.medical),shelter_capacity_available:Number(stock.shelter),transport_capacity_fraction:Number(transport),priority_overrides:po})}); setResult(data); localStorage.setItem("disaster_ai_last_optimization",JSON.stringify(data)); }catch(e){setError(e.message);}finally{setLoading(false);} }
  return <div><PageHeader title="Optimization Planner" subtitle="Allocate shared relief inventory across multiple zones using Google OR-Tools linear programming."/>
    <section className="panel optimizer-intro"><div><span className="eyebrow">MULTI-ZONE OPTIMIZATION</span><h3>Choose disaster zones</h3><p>Select 2–8 zones and optionally elevate their priority.</p></div><label>Disaster type<select value={type} onChange={e=>setType(e.target.value)}><option value="">All disaster types</option>{types.map(t=><option key={t}>{t}</option>)}</select></label></section>
    <ErrorBlock error={error}/><div className="optimizer-zone-grid">{records.map(r=><button type="button" key={r.row_id} className={`optimizer-zone-card ${selected.includes(r.row_id)?"selected":""}`} onClick={()=>toggle(r.row_id)}><div className="optimizer-zone-top"><span>#{r.row_id}</span><span className="disaster-chip">{r.disaster_type}</span></div><strong>{r.disaster_subtype}</strong><div className="optimizer-zone-stats"><span>Affected<b>{Number(r.affected_population||0).toLocaleString()}</b></span><span>Severity<b>{Number(r.severity_score||0).toFixed(3)}</b></span><span>DRIS<b>{Number(r.dris_score||0).toFixed(2)}</b></span></div><div className="optimizer-select-text">{selected.includes(r.row_id)?"✓ Selected":"Select zone"}</div></button>)}</div>
    {selectedRows.length>0&&<section className="panel"><div className="panel-heading"><div><h3>Priority Overrides</h3><p>1.0 is normal; increase up to 3.0.</p></div></div><div className="optimizer-override-list">{selectedRows.map(r=><div className="optimizer-override-row" key={r.row_id}><div><strong>#{r.row_id} · {r.disaster_type}</strong><span>{r.disaster_subtype}</span></div><label>Multiplier<input type="number" min="0.5" max="3" step="0.1" value={overrides[r.row_id]??1} onChange={e=>setOverrides({...overrides,[r.row_id]:Math.min(3,Math.max(.5,Number(e.target.value)||1))})}/></label></div>)}</div></section>}
    <section className="panel"><div className="panel-heading"><div><h3>Shared Relief Inventory</h3><p>Prefilled from Resource Inventory; you may change values for this planning run.</p></div></div><div className="optimizer-inventory-grid"><label>Food packets<input type="number" min="0" value={stock.food} onChange={e=>setStock({...stock,food:e.target.value})}/></label><label>Water litres<input type="number" min="0" value={stock.water} onChange={e=>setStock({...stock,water:e.target.value})}/></label><label>Medical kits<input type="number" min="0" value={stock.medical} onChange={e=>setStock({...stock,medical:e.target.value})}/></label><label>Shelter capacity<input type="number" min="0" value={stock.shelter} onChange={e=>setStock({...stock,shelter:e.target.value})}/></label></div><div className="optimizer-slider"><div><strong>Transport capacity</strong><span>{Math.round(transport*100)}% of normal</span></div><input type="range" min="0.1" max="1" step="0.05" value={transport} onChange={e=>setTransport(Number(e.target.value))}/></div><button className="primary-button" onClick={run} disabled={loading}>{loading?"Optimizing...":`Run OR-Tools Optimization (${selected.length} zones)`}</button></section>
    {loading&&<LoadingBlock text="Solving multi-zone allocation model..."/>}
    {result&&<><div className="result-banner"><div><span className="eyebrow">OPTIMIZATION RESULT</span><h2>{result.feature}</h2><p>{result.solver}</p></div><StatusBadge value={result.solver_status}/></div><div className="metrics-grid"><MetricCard label="Zones Optimized" value={result.selected_zone_count}/><MetricCard label="Overall Coverage" value={`${result.overall_coverage_percent}%`}/><MetricCard label="Transport Capacity" value={`${Math.round(result.transport_capacity_fraction*100)}%`}/><MetricCard label="Solver" value={result.solver_status}/></div><section className="panel"><div className="table-container"><table className="data-table"><thead><tr><th>Resource</th><th>Inventory</th><th>Demand</th><th>Allocated</th><th>Unmet</th><th>Coverage</th></tr></thead><tbody>{Object.keys(LABELS).map(k=><tr key={k}><td>{LABELS[k]}</td><td>{Number(result.shared_inventory[k]||0).toLocaleString()}</td><td>{Number(result.total_predicted_demand[k]||0).toLocaleString()}</td><td>{Number(result.total_optimized_allocation[k]||0).toLocaleString()}</td><td className={result.total_unmet_demand[k]>0?"danger-text":"success-text"}>{Number(result.total_unmet_demand[k]||0).toLocaleString()}</td><td>{result.coverage_percent[k]}%</td></tr>)}</tbody></table></div></section><section className="panel"><div className="panel-heading"><div><h3>Zone Allocation Plan</h3></div></div><div className="optimizer-results-list">{result.zones.map(z=><article className="optimizer-result-card" key={z.row_id}><div className="optimizer-result-header"><div><span className="disaster-chip">{z.disaster_type}</span><h4>Zone #{z.row_id}</h4><p>Priority {z.base_priority_score}/100 · Override {z.manual_priority_multiplier}× · Deliverability {(z.deliverability_factor*100).toFixed(0)}%</p></div><strong className="optimizer-coverage-score">{z.average_zone_coverage_percent}%<small>avg. coverage</small></strong></div></article>)}</div><div className="note-box">{result.note}</div></section></>}
  </div>;
}
